### ISSUE TITLE
Error Route not Found: Try /metrics in Grafana dashbord

### ISSUE THREAD

**Issue by techyhard** [homeylab/tdarr-exporter#26]
Hi,

Thanks for this exporter, I have it running and pulling from a local TDarr and see info coming from HTTP://ip:8265/metrics so know its connected... BUT when I import the Grafana dashboard I get a 'Route not Found: Try /metrics ' error... I have set up the connection to Prometheus to the docker image but cant get it to connect... Any ideas? All components are running in docker and using host network.

Thanks in advance.

**Comment by pchang388** [comment]
hi @techyhard sorry for the delay in getting to this

Hmm I haven't seen this issue before, since you are using docker - how is your Prometheus target set to scrape the container?

![image](https://github.com/homeylab/tdarr-exporter/assets/51681873/363285fc-cb9f-4131-ac1c-e112736eaa6d)

Does it look something similar to below and has the path specified? From what I can tell with my limited visibility, it appears that your Prometheus instance is actually scraping the `/` path or other, since that will return a message similar to what you see.

**Comment by pchang388** [comment]
It's been some time since this ticket was opened. If the issue persists even after doing some digging like I've suggested, please open a new issue. Thanks!
