### ISSUE TITLE
Unable to exec into Docker container

### ISSUE THREAD

**Issue by ShawnHardwick** [homeylab/tdarr-exporter#27]
I have a docker compose definition defined below for a running tdarr-exporter container:
```
  tdarr-exporter:
    container_name: tdarr-exporter
    image: homeylab/tdarr-exporter:latest   
    restart: always
    environment:
      - TDARR_URL=http://tdarr
    ports:
      - 9091:9090
 ```
 
 I'd like to enter into the docker container like I do with many of my other containers to do some troubleshooting. However, this container is configured differently and not allowing entry.
 
 ```
# docker exec -it tdarr-exporter /bin/bash
OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown
# docker exec -it tdarr-exporter /bin/sh
OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown
```

Any idea what is going on here?

**Comment by pchang388** [comment]
hey @ShawnHardwick

Thanks for opening the issue! This is a purposeful design decision and leverages [distroless](https://github.com/GoogleContainerTools/distroless) containers. The exclusion of shells (bash, sh, etc) is a common practice for creating executables like this exporter.

I'm not so sure what benefit you might have from digging around in the container since it's just a binary copied over after being compiled, but you also have the option to install the binary directly via release notes. You could do that and then run it locally for troubleshooting.

Feel free to drop your problems here as well, I can take a look and help with the troubleshooting!

**Comment by ShawnHardwick** [comment]
Thanks for the quick response. I guess this is my first experience with a distroless container.

I was looking to exec into the container to troubleshoot some DNS lookup issues since it could've find my `Tdarr` instance container. I eventually figured out the syntax to use (I was missing the port and I couldn't use my Docker hostname either) so I no longer need this anymore.
